export const data = [
  {
    type: "Bicycle",
    name: "BMX",
    price: 122,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "Trek Bicycle Coporation",
    price: 1210,
    description: "good bike",
    manufacturer: "Trek",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Scooter",
    name: "Adiva",
    price: 12000,
    description: "good scooter Adiva",
    manufacturer: "Italy",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "BMX",
    price: 138,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "BMX",
    price: 137,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "BMX",
    price: 136,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "BMX",
    price: 135,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "BMX",
    price: 134,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "BMX",
    price: 133,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "BMX",
    price: 131,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "BMX",
    price: 130,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
];
