export const data = [
  {
    type: "Bicycle",
    name: "BMX",
    price: 125,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Scooter",
    name: "BMX",
    price: 12500,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "BMX",
    price: 130,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "BMX",
    price: 130,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
  {
    type: "Bicycle",
    name: "BMX",
    price: 130,
    description: "good bike",
    manufacturer: "BMX",
    max_speed: 20,
    weight: 5.2,
    wheel_size: 1.25,
    quantity: 10,
  },
];
